### PR TITLE
Added count and sum to the metric_value model

### PR DESCRIPTION
**Pull request by oOoHoCo**
I needed to get the count and sum of metrics (like in the Appdynamics UI), so this was added to metric_value.py

### CODE REVIEW

**Comment by kylefurlong** [comment]
Hi oOoHoCo,

Happy to merge, but could you clean up the whitespace though, I notice there's an extra line break added, and the indentation is a bit off.

Thanks and regards,
Kyle

**Comment by oOoHoCo** [comment]
Hi kylefurlong,
looks like its good now. Thanks for the advice.

Happy, that you'd like to merge this addition.

Kind regards,

Ben

**Comment by oOoHoCo** [comment]
@kylefurlong I would like to ask how long it takes until this gets merged? :D

**Comment by kylefurlong** [comment]
@oOoHoCo Done.

**Pull request merged**
